---
- name: Ensure onlyoffice namespace exists
  shell: "kubectl create namespace onlyoffice --dry-run=client -o yaml | kubectl apply -f -"
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  changed_when: false

- name: Transfer OnlyOffice deployment manifest
  template:
    src: deploy.yaml.j2
    dest: /tmp/onlyoffice-deploy.yaml

- name: Apply OnlyOffice deployment
  shell: "kubectl apply -f /tmp/onlyoffice-deploy.yaml -n onlyoffice"
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
